// Complete ISO 3166-1 country name → alpha-2 code map, plus common aliases (usa/uk/uae/…).
// Shared by the Meta targeting mapper (geo_locations.countries) and available to the Google mapper.
// Keys are lowercased; look up with name.trim().toLowerCase(). This replaces the old 12-country
// inline map in metaTargetingMapper.ts so a user typing "Spain"/"Nigeria"/etc. no longer silently
// collapses to US.
export const COUNTRY_NAME_TO_CODE: Record<string, string> = {
  afghanistan: "AF", "aland islands": "AX", albania: "AL", algeria: "DZ", "american samoa": "AS",
  andorra: "AD", angola: "AO", anguilla: "AI", antarctica: "AQ", "antigua and barbuda": "AG",
  argentina: "AR", armenia: "AM", aruba: "AW", australia: "AU", austria: "AT", azerbaijan: "AZ",
  bahamas: "BS", bahrain: "BH", bangladesh: "BD", barbados: "BB", belarus: "BY", belgium: "BE",
  belize: "BZ", benin: "BJ", bermuda: "BM", bhutan: "BT", bolivia: "BO",
  "bosnia and herzegovina": "BA", botswana: "BW", "bouvet island": "BV", brazil: "BR",
  "british indian ocean territory": "IO", "brunei": "BN", "brunei darussalam": "BN", bulgaria: "BG",
  "burkina faso": "BF", burundi: "BI", "cabo verde": "CV", "cape verde": "CV", cambodia: "KH",
  cameroon: "CM", canada: "CA", "cayman islands": "KY", "central african republic": "CF", chad: "TD",
  chile: "CL", china: "CN", "christmas island": "CX", "cocos islands": "CC", colombia: "CO",
  comoros: "KM", congo: "CG", "democratic republic of the congo": "CD", "cook islands": "CK",
  "costa rica": "CR", "cote d'ivoire": "CI", "ivory coast": "CI", croatia: "HR", cuba: "CU",
  curacao: "CW", cyprus: "CY", "czech republic": "CZ", czechia: "CZ", denmark: "DK", djibouti: "DJ",
  dominica: "DM", "dominican republic": "DO", ecuador: "EC", egypt: "EG", "el salvador": "SV",
  "equatorial guinea": "GQ", eritrea: "ER", estonia: "EE", eswatini: "SZ", swaziland: "SZ",
  ethiopia: "ET", "falkland islands": "FK", "faroe islands": "FO", fiji: "FJ", finland: "FI",
  france: "FR", "french guiana": "GF", "french polynesia": "PF", gabon: "GA", gambia: "GM",
  georgia: "GE", germany: "DE", ghana: "GH", gibraltar: "GI", greece: "GR", greenland: "GL",
  grenada: "GD", guadeloupe: "GP", guam: "GU", guatemala: "GT", guernsey: "GG", guinea: "GN",
  "guinea-bissau": "GW", guyana: "GY", haiti: "HT", honduras: "HN", "hong kong": "HK", hungary: "HU",
  iceland: "IS", india: "IN", indonesia: "ID", iran: "IR", iraq: "IQ", ireland: "IE",
  "isle of man": "IM", israel: "IL", italy: "IT", jamaica: "JM", japan: "JP", jersey: "JE",
  jordan: "JO", kazakhstan: "KZ", kenya: "KE", kiribati: "KI", kuwait: "KW", kyrgyzstan: "KG",
  laos: "LA", latvia: "LV", lebanon: "LB", lesotho: "LS", liberia: "LR", libya: "LY",
  liechtenstein: "LI", lithuania: "LT", luxembourg: "LU", macau: "MO", macao: "MO", madagascar: "MG",
  malawi: "MW", malaysia: "MY", maldives: "MV", mali: "ML", malta: "MT", "marshall islands": "MH",
  martinique: "MQ", mauritania: "MR", mauritius: "MU", mayotte: "YT", mexico: "MX", micronesia: "FM",
  moldova: "MD", monaco: "MC", mongolia: "MN", montenegro: "ME", montserrat: "MS", morocco: "MA",
  mozambique: "MZ", myanmar: "MM", burma: "MM", namibia: "NA", nauru: "NR", nepal: "NP",
  netherlands: "NL", "new caledonia": "NC", "new zealand": "NZ", nicaragua: "NI", niger: "NE",
  nigeria: "NG", niue: "NU", "norfolk island": "NF", "north korea": "KP", "north macedonia": "MK",
  macedonia: "MK", "northern mariana islands": "MP", norway: "NO", oman: "OM", pakistan: "PK",
  palau: "PW", palestine: "PS", panama: "PA", "papua new guinea": "PG", paraguay: "PY", peru: "PE",
  philippines: "PH", poland: "PL", portugal: "PT", "puerto rico": "PR", qatar: "QA", reunion: "RE",
  romania: "RO", russia: "RU", "russian federation": "RU", rwanda: "RW", "saint kitts and nevis": "KN",
  "saint lucia": "LC", "saint vincent and the grenadines": "VC", samoa: "WS", "san marino": "SM",
  "sao tome and principe": "ST", "saudi arabia": "SA", senegal: "SN", serbia: "RS", seychelles: "SC",
  "sierra leone": "SL", singapore: "SG", "sint maarten": "SX", slovakia: "SK", slovenia: "SI",
  "solomon islands": "SB", somalia: "SO", "south africa": "ZA", "south korea": "KR", korea: "KR",
  "south sudan": "SS", spain: "ES", "sri lanka": "LK", sudan: "SD", suriname: "SR", sweden: "SE",
  switzerland: "CH", syria: "SY", taiwan: "TW", tajikistan: "TJ", tanzania: "TZ", thailand: "TH",
  "timor-leste": "TL", "east timor": "TL", togo: "TG", tokelau: "TK", tonga: "TO",
  "trinidad and tobago": "TT", tunisia: "TN", turkey: "TR", turkiye: "TR", turkmenistan: "TM",
  "turks and caicos islands": "TC", tuvalu: "TV", uganda: "UG", ukraine: "UA",
  "united arab emirates": "AE", uae: "AE", "united kingdom": "GB", uk: "GB", "great britain": "GB",
  britain: "GB", "united states": "US", "united states of america": "US", usa: "US", "u.s.": "US",
  "u.s.a.": "US", america: "US", uruguay: "UY", uzbekistan: "UZ", vanuatu: "VU", "vatican city": "VA",
  venezuela: "VE", vietnam: "VN", "viet nam": "VN", "western sahara": "EH", yemen: "YE", zambia: "ZM",
  zimbabwe: "ZW",
};
