import { useMemo, useState } from "react";
import { Link } from "react-router-dom";

const CATEGORIES = [
  {
    name: "E-commerce",
    blurb: "Product-led creative and retargeting built around your catalog and average order value.",
  },
  {
    name: "Local services",
    blurb: "Radius targeting and call/booking-focused creative for restaurants, salons, gyms, and clinics.",
  },
  {
    name: "SaaS & services",
    blurb: "Lead-gen audiences and messaging tuned to your goals, from demos booked to trials started.",
  },
  {
    name: "Apps",
    blurb: "Install and engagement campaigns split across networks based on where your users actually are.",
  },
];

const BENEFITS = [
  {
    title: "Zero manual bidding",
    body: "AdGo builds the audiences, budget split, and creatives — you approve, it launches.",
  },
  {
    title: "One dashboard, two networks",
    body: "Google Ads and Meta campaigns launch and report from the same place, no tab-switching.",
  },
  {
    title: "Budget moves on its own",
    body: "A bandit algorithm exploits your best-converting variant, explores the rest, and pauses high-CPA ones automatically.",
  },
  {
    title: "Pay for what it manages",
    body: "A flat monthly fee plus a percentage of spend under management — nothing to configure.",
  },
];

const FAQS = [
  {
    q: "Do I need an Anthropic API key to use this?",
    a: "No. Strategy generation uses Claude when a key is configured, and falls back to a deterministic strategy engine otherwise — the full flow works either way.",
  },
  {
    q: "Which ad networks does AdGo support?",
    a: "Google Ads and Meta today. Adapters make live API calls once credentials are configured, and use mock data otherwise so you can try the full flow first.",
  },
  {
    q: "How does the budget optimization actually work?",
    a: "An epsilon-greedy bandit reviews performance per variant, shifts spend toward the best-converting one, keeps exploring the others, and pauses anything with a high cost per acquisition.",
  },
  {
    q: "How is this billed?",
    a: "A flat base fee plus a percentage of ad spend AdGo manages on your behalf — generated as a monthly invoice from real campaign spend.",
  },
];

function currency(n: number): string {
  return n.toLocaleString("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
}

export default function Landing() {
  const [budget, setBudget] = useState(2000);
  const [cpa, setCpa] = useState(40);

  const { reclaimed, extraConversions } = useMemo(() => {
    const reclaimedBudget = Math.round(budget * 0.15);
    const conversions = cpa > 0 ? Math.round(reclaimedBudget / cpa) : 0;
    return { reclaimed: reclaimedBudget, extraConversions: conversions };
  }, [budget, cpa]);

  return (
    <div className="landing">
      <header className="landing-nav">
        <Link to="/" className="brand">
          AdGo
        </Link>
        <nav className="landing-nav-links">
          <a href="#how-it-works">How it works</a>
          <a href="#pricing">Pricing</a>
          <a href="#faq">FAQ</a>
          <Link to="/get-started" className="btn btn-primary">
            Get started
          </Link>
        </nav>
      </header>

      <section className="hero">
        <span className="eyebrow">AI-driven ad automation</span>
        <h1>Describe your business. Let AI run your ads.</h1>
        <p className="lead">
          AdGo generates a full ad strategy from a short business description, launches it across Google and Meta,
          and continuously reallocates your budget toward what's actually converting.
        </p>
        <div className="hero-actions">
          <Link to="/get-started" className="btn btn-primary btn-lg">
            Get started free
          </Link>
          <a href="#how-it-works" className="btn btn-secondary btn-lg">
            See how it works
          </a>
        </div>
        <p className="hero-note">No credit card required to try the full flow.</p>
      </section>

      <div className="trust-strip">
        <span className="trust-chip">Runs on Google Ads</span>
        <span className="trust-chip">Runs on Meta Ads</span>
        <span className="trust-chip">Strategy generated by Claude</span>
        <span className="trust-chip">Usage-based billing</span>
      </div>

      <section className="section" id="how-it-works">
        <div className="section-header">
          <h2>How it works</h2>
          <p>From a business description to a live, self-optimizing campaign in three steps.</p>
        </div>
        <div className="steps">
          <div className="step">
            <div className="step-number">1</div>
            <h3>Tell us about your business</h3>
            <p>Name, industry, monthly budget, and goals — that's all the strategy engine needs to start.</p>
          </div>
          <div className="step">
            <div className="step-number">2</div>
            <h3>AI builds your strategy</h3>
            <p>Claude generates recommended networks, a budget split, target audiences, and ad creatives.</p>
          </div>
          <div className="step">
            <div className="step-number">3</div>
            <h3>We launch and optimize</h3>
            <p>Campaigns go live on Google and Meta, then a bandit algorithm shifts budget toward what wins.</p>
          </div>
        </div>
      </section>

      <section className="section section-alt">
        <div className="section-header">
          <h2>Built for how you sell</h2>
          <p>Tell AdGo your industry and it tailors targeting and creative accordingly.</p>
        </div>
        <div className="category-grid">
          {CATEGORIES.map((c) => (
            <div className="category-card" key={c.name}>
              <h3>{c.name}</h3>
              <p>{c.blurb}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="section" id="calculator">
        <div className="section-header">
          <h2>See what automated optimization could reclaim</h2>
          <p>A rough estimate of budget AdGo's bandit optimizer could shift away from underperforming variants.</p>
        </div>
        <div className="calculator">
          <div className="calculator-inputs">
            <label>
              Monthly ad budget (USD)
              <input
                type="number"
                min={100}
                step={100}
                value={budget}
                onChange={(e) => setBudget(Math.max(0, Number(e.target.value)))}
              />
            </label>
            <label>
              Typical cost per conversion (USD)
              <input
                type="number"
                min={1}
                step={1}
                value={cpa}
                onChange={(e) => setCpa(Math.max(0, Number(e.target.value)))}
              />
            </label>
          </div>
          <div className="calculator-result">
            <span className="big-number">{currency(reclaimed)}/mo</span>
            <span className="result-label">reclaimed from underperforming variants</span>
            <div className="result-secondary">
              <span className="big-number">~{extraConversions}</span>
              <span className="result-label">additional conversions/mo at your current CPA</span>
            </div>
            <p className="calculator-disclaimer">
              Illustrative estimate based on typical bandit-optimization reallocation — actual results depend on
              your campaigns.
            </p>
          </div>
        </div>
      </section>

      <section className="section section-alt">
        <div className="section-header">
          <h2>Why teams use AdGo</h2>
        </div>
        <div className="benefits-grid">
          {BENEFITS.map((b) => (
            <div className="benefit-card" key={b.title}>
              <h3>{b.title}</h3>
              <p>{b.body}</p>
            </div>
          ))}
        </div>
      </section>

      <section className="section" id="pricing">
        <div className="section-header">
          <h2>Simple, usage-based pricing</h2>
          <p>One plan. No contracts.</p>
        </div>
        <div className="pricing-card">
          <div className="pill">Platform fee</div>
          <div className="price">
            $49<span>/mo + 12% of managed ad spend</span>
          </div>
          <ul>
            <li>AI-generated strategy and creatives</li>
            <li>Launch and manage campaigns on Google &amp; Meta</li>
            <li>Automated budget optimization</li>
            <li>Monthly invoicing based on real spend</li>
          </ul>
          <Link to="/get-started" className="btn btn-primary btn-lg">
            Get started free
          </Link>
        </div>
      </section>

      <section className="section section-alt" id="faq">
        <div className="section-header">
          <h2>Frequently asked questions</h2>
        </div>
        <div className="faq">
          {FAQS.map((f) => (
            <details className="faq-item" key={f.q}>
              <summary>{f.q}</summary>
              <p>{f.a}</p>
            </details>
          ))}
        </div>
      </section>

      <section className="cta-banner">
        <div className="cta-banner-inner">
          <h2>Ready to put your ad spend on autopilot?</h2>
          <p>Set up your business and get a full ad strategy in minutes.</p>
          <Link to="/get-started" className="btn btn-primary btn-lg">
            Get started free
          </Link>
        </div>
      </section>

      <footer className="landing-footer">
        <span>AdGo — AI Ad Automation</span>
        <span>© {new Date().getFullYear()}</span>
      </footer>
    </div>
  );
}
